/*
PROJECT: Supply Chain Data Modeling & Transformation
AUTHOR: [Your Name]
DESCRIPTION: 
    - ETL Process transforming raw TPC-H data (3rd Normal Form) into a Star Schema.
    - Optimized for Analytics/BI by reducing join complexity.
    - Source: Snowflake Sample Data (TPCH_SF1).
*/

-- 1. SET UP THE ENVIRONMENT
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE SUPPLY_CHAIN_DW;
CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DW.ANALYTICS;
USE WAREHOUSE COMPUTE_WH;

-- 2. CREATE DIMENSION TABLE (DIM_CUSTOMER)
-- Logic: Denormalize Customer, Nation, and Region to remove 2 joins.
CREATE OR REPLACE TABLE SUPPLY_CHAIN_DW.ANALYTICS.DIM_CUSTOMER AS
SELECT 
    c.C_CUSTKEY as CUSTOMER_ID,
    c.C_NAME as CUSTOMER_NAME,
    c.C_MKTSEGMENT as MARKET_SEGMENT,
    c.C_PHONE as PHONE,
    n.N_NAME as NATION,
    r.R_NAME as REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n 
    ON c.C_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r 
    ON n.N_REGIONKEY = r.R_REGIONKEY;

-- 3. CREATE FACT TABLE (FCT_SALES)
-- Logic: Combine Orders and LineItems; Pre-calculate Net Revenue.
CREATE OR REPLACE TABLE SUPPLY_CHAIN_DW.ANALYTICS.FCT_SALES AS
SELECT 
    l.L_ORDERKEY as ORDER_ID,
    l.L_LINENUMBER as LINE_ITEM_ID,
    o.O_CUSTKEY as CUSTOMER_ID,
    o.O_ORDERDATE as ORDER_DATE,
    l.L_PARTKEY as PART_ID,
    l.L_SUPPKEY as SUPPLIER_ID,
    l.L_QUANTITY as QUANTITY,
    l.L_EXTENDEDPRICE as REVENUE,
    l.L_DISCOUNT as DISCOUNT,
    (l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) as NET_REVENUE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
    ON l.L_ORDERKEY = o.O_ORDERKEY;

-- 4. PERFORMANCE & VALIDATION
-- This section demonstrates the efficiency gain of the Star Schema.

-- Query A: The Old Way (Slow, 5 Joins)
-- SELECT r.R_NAME, SUM(l.L_EXTENDEDPRICE)
-- FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
-- JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o ON l.L_ORDERKEY = o.O_ORDERKEY
-- JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
-- JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
-- JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
-- GROUP BY r.R_NAME;

-- Query B: The New Way (Fast, 1 Join)
-- SELECT c.REGION, SUM(f.REVENUE)
-- FROM SUPPLY_CHAIN_DW.ANALYTICS.FCT_SALES f
-- JOIN SUPPLY_CHAIN_DW.ANALYTICS.DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
-- GROUP BY c.REGION;